#include<iostream>
using namespace std;
int main()
{
    int a=1000,b=500,c=300,d=40;
    if(a>b)
    {
        if(a>c)
        {
            if(a>d)
            {
                cout<<"a";
            }
            else{
                cout<<"d";
            }
        }
        else{
            if(c>d)
            {
                cout<<"c";
            }
            else{
                cout<<"d";
            }
        }
    }
    else{
        if(b>c)
        {
            if(b>d)
            {
                cout<<"b";
            }
            else
            {
                cout<<"d";
            }
        }
        else{
            if(c>d)
            {
                cout<<"c";
            }
            else
            {
                cout<<"d";
            }
        }
    }
}