#include<iostream>
using namespace std;
int main()
{
    int a=100,b=200,c=300,d=400,e=500;
    if(a>b)
    {
        if(a>c)
        {
            if(a>d)
            {
                if(a>e)
                {
                    cout<<"a";
                }
                else{
                    cout<<"e";
                }
            }
            else
            {
                if(d>e)
                {
                    cout<<"d";
                }
                else{
                    cout<<"e";
                }
            }
        }
        else
        {
            if(c>d)
            {
                if(c>e)
                {
                    cout<<"c";
                }
                else{
                    cout<<"e";
                }
            }
            else
            {
                if(d>e)
                {
                    cout<<"d";
                }
                else
                {
                    cout<<"e";
                }
            }
        }
    }
    else
    {
        if(b>c)
        {
            if(b>d)
            {
                if(b>e)
                {
                    cout<<"b";
                }
                else{
                    cout<<"e";
                }
            }
            else{
                if(d>e)
                {
                    cout<<"d";
                }
                else{
                    cout<<"e";
                }
            }
        }
        else
        {
            if(c>d)
            {
                if(c>e)
                {
                    cout<<"c";
                }
                else{
                    cout<<"e";
                }
            }
            else{
                if(d>e)
                {
                    cout<<"d";
                }
                else{
                    cout<<"e";
                }
            }
        }
    }
}